### ISSUE TITLE
name 'solo' is not defined

### ISSUE THREAD

**Issue by CajKos** [Solo-FL/SoloPy#10]
Hi,

I am just getting started with the Solo Uno and wired it to my Raspberry Pi 4. I did the installation procedure as documented on the github but when I want to test the examples I am getting the error as shown:

`Traceback (most recent call last):
  File "reading_temperature.py", line 38, in <module>
    do_work()
  File "reading_temperature.py", line 34, in do_work
    __setup()
  File "reading_temperature.py", line 29, in __setup
    __solo_driver = solo.SoloMotorController(__solo_address)
NameError: name 'solo' is not defined`

I also wired a brushed dc motor to the solo and my piano settings are all DOWN except for switch 3. The motor is then continuously running.

Thanks for any help!

**Comment by Solo-FL** [comment]
Hi CajKos, we fix the issue in the examples. Please try to use the last version of it.

**Comment by CajKos** [comment]
Thanks a lot! Now it works.
