### ISSUE TITLE
BLDC_encoder

### ISSUE THREAD

**Issue by Himani48** [Solo-FL/SoloPy#12]
Hello, I am using Brushless Frameless Motor 50BLF15,  for this i am using this file and modify as motor requirement examples/windows/usb/PMSM_Speed_Control_Encoder_based.py . When i run program motor is not work in clockwise direction and if i'm work on at counterclockwise direction with removing C.C. part its stop sometimes and take minute to rerun while loop. what should i add for not stopping motor again and again. Also, i need stall detection error time out i add command but its not working. What is the problem? 

Here, i wrote my code below.

# Copyright: (c) 2021, 2022, 2023 SOLO motor controllers project
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

# Title: SoloPy
# Author: SOLOMotorControllers
# Date: 2023
# Code version: 3.0.0
# Availability: https://github.com/Solo-FL/SoloPy/tree/main/SoloPy
# This Library is made by SOLOMotorControllers.COM
# please visit:  https://www.SOLOMotorControllers.com/

# The Motor used for Testings: teknic m-2310P-LN-04K

import SoloPy as solo

import time

# instanciate a SOLO object:
mySolo = solo.SoloMotorControllerUart("COM5", 0, solo.UART_BAUD_RATE.RATE_937500)

# Desired Switching or PWM Frequency at Output
pwmFrequency = 20

# Motor's Number of Poles
numberOfPoles = 20

# Motor's Number of Encoder Lines (PPR pre-quad)
numberOfEncoderLines = 2048

# Speed controller Kp
speedControllerKp = 0.7

# Speed controller Ki
speedControllerKi = 0.003

# Position controller Kp
positionControllerKp = 0.12

# Position controller Ki
positionControllerKi = 0.02

# Current Limit of the Motor
currentLimit_init = 15

# Battery or Bus Voltage
busVoltage = 0

# Motor Torque feedback
actualMotorTorque = 0

# Motor speed feedback
actualMotorSpeed = 0

# Motor position feedback
actualMotorPosition = 0

# wait here till communication is established
print("Trying to Connect To SOLO")
communication_is_working = False
while communication_is_working is False:
    time.sleep(1)
    communication_is_working, error = mySolo.communication_is_working()
print("Communication Established succuessfully!")

# Initial Configuration of the device and the Motor
mySolo.set_output_pwm_frequency_khz(pwmFrequency)
mySolo.set_current_limit(currentLimit_init)
mySolo.set_motor_poles_counts(numberOfPoles)
mySolo.set_incremental_encoder_lines(numberOfEncoderLines)
mySolo.set_command_mode(solo.COMMAND_MODE.DIGITAL)
mySolo.set_motor_type(solo.MOTOR_TYPE.BLDC_PMSM)
mySolo.set_feedback_control_mode(solo.FEEDBACK_CONTROL_MODE.ENCODERS)
time.sleep(3)
mySolo.set_speed_controller_kp(speedControllerKp)
mySolo.set_speed_controller_ki(speedControllerKi)
mySolo.set_control_mode(solo.CONTROL_MODE.SPEED_MODE)

# run the motor identification to Auto-tune the current controller gains Kp and Ki needed for Torque Loop
# run ID. always after selecting the Motor Type!
# ID. doesn't need to be called everytime, only one time after wiring up the Motor will be enough
# the ID. values will be remembered by SOLO after power recycling
mySolo.motor_parameters_identification(solo.ACTION.START)
print("Identifying the Motor")
# wait at least for 2sec till ID. is done
time.sleep(2)

# Perform Encoder calibration
mySolo.sensor_calibration(solo.POSITION_SENSOR_CALIBRATION_ACTION.INCREMENTAL_ENCODER_START_CALIBRATION)
#t TODO: write while sensor_calibration.... and remove sleep(35)
time.sleep(35)

mySolo.set_speed_controller_kp(speedControllerKp)
mySolo.set_speed_controller_ki(speedControllerKi)
mySolo.set_control_mode(solo.CONTROL_MODE.SPEED_MODE)
enc_off_ccw = mySolo.get_encoder_hall_ccw_offset()
enc_off_cw = mySolo.get_encoder_hall_cw_offset()
print('encoder offsets cw, ccw: ' + str(enc_off_cw) + str(enc_off_ccw))
mySolo.set_speed_acceleration_value(30.0)
mySolo.set_speed_deceleration_value(30.0)

# Current Limit of the Motor
currentLimit_run = 20
mySolo.set_current_limit(currentLimit_run)

# loop actions
while True:

    # set the Direction on C.C.W.
    mySolo.set_motor_direction(solo.DIRECTION.COUNTERCLOCKWISE)
    # set an arbitrary Positive speed reference[RPM]
    mySolo.set_speed_reference(100)
    time.sleep(1)
    actualMotorSpeed, error = mySolo.get_speed_feedback()
    print("Motor Speed: " + str(actualMotorSpeed))
    actualMotorTorque, error = mySolo.get_quadrature_current_iq_feedback()
    print("Measured Iq/Torque[A]: " + str(actualMotorTorque))
    time.sleep(3)

    # set an arbitrary Positive speed reference[RPM]
    mySolo.set_speed_reference(0)
    time.sleep(1)
    actualMotorSpeed, error = mySolo.get_speed_feedback()
    print("Motor Speed: " + str(actualMotorSpeed))
    actualMotorTorque, error = mySolo.get_quadrature_current_iq_feedback()
    print("Measured Iq/Torque[A]: " + str(actualMotorTorque))
    time.sleep(3)

    error_detection, error  = mySolo.get_error_register()
    print("Stall detection error detected:" + str(error))
    time.sleep(4)

**Comment by Solo-FL** [comment]
It look like a calibration problem, 
I sugest you to find the [correct set-up using Motion terminal](https://www.solomotorcontrollers.com/blog/setup-tune-motors-using-solo-motion-terminal/) then you can avoid to set-up the value in your code as they will memorized inside the SOLO. 

This will probably solve the C.C. issue. 
Can be important to list motor type, encoder type, and other important information but in any case I suggest using the [forum section](https://www.solomotorcontrollers.com/forum/solo-python-raspberry-pi-library/) where you can find some interesting information too
